remote_theme: pmarsceill/just-the-docs

search_enabled: false
ga_tracking: UA-145781573-1

title: Pull Assistant
description: A Jekyll theme for documentation
aux_links:
    "Pull Assistant github app":
      - "https://github.com/apps/pull-assistant"
